### ISSUE TITLE
Group command (group.command)

### ISSUE THREAD

**Issue by FFY00** [boolangery/d-rpc#2]
Hey,

Is the library currently able to handle commands like `auth.login`?

Thank you,
Filipe

**Comment by FFY00** [comment]
Nevermind, I have `@rpcMethod('auth.login')`. This is the only way to do it, right?

**Comment by boolangery** [comment]
Hey,

Yea for now this is the only way to do it. I need to write some doc :)

And contributions are welcome, and are greatly appreciated :)

**Comment by FFY00** [comment]
If I have some time I'll certainly help with this :smile:!
