### ISSUE TITLE
How to deal with more complex data structures?

### ISSUE THREAD

**Issue by FFY00** [boolangery/d-rpc#3]
Right now I am interfacing with Deluge and the response data structures can be a bit complex.
Is it possible to define a `struct` for this kind of things?

Example:
```
{
   "id":"1",
   "result":{
      "files":[
         {
            "index":0,
            "path":"folder/file0",
            "offset":0,
            "size":474588414
         },
         {
            "index":1,
            "path":"folder/file1",
            "offset":474588414,
            "size":433520320
         },
         {
            "index":2,
            "path":"folder/file2",
            "offset":908108734,
            "size":457965061
         }
         ...
      ],
      "is_finished":true,
      "save_path":"some/path"
   },
   "error":null
}
```

A good approach for this would be to have a deserializer.
Ex. https://github.com/libmir/asdf

**Comment by boolangery** [comment]
Hey,
It use vibed json serializer [vibe.data.json](http://vibed.org/api/vibe.data.json/)
I added a more complex [example](https://github.com/boolangery/d-rpc/blob/master/examples/tcp_client/source/app.d#L27).
